In [1]:
from DANZEM import utils
from DANZEM import data
from DANZEM import lgp

import importlib

utils.SetDir('C:\\Users\\tahjaa\\Documents\\Research\\DANZEM\\DANZEM\\data')
utils.DATA_BASE_DIR

'C:\\Users\\tahjaa\\Documents\\Research\\DANZEM\\DANZEM\\data'

In [2]:
#importlib.reload(lgp)

def GetDemand(day):
    df = data.GetLGPFile(day)
    return lgp.ExtractLoadInfo(df)

demand_df = GetDemand((2017, 1, 1))
demand_df.head()

               NI Load (MW)  SI Load (MW)
tpid
2017_01_01_01      1785.563      1451.458
2017_01_01_02      1681.077      1429.073
2017_01_01_03      1584.498      1404.121
2017_01_01_04      1518.693      1371.177
2017_01_01_05      1476.998      1350.335

In [4]:
importlib.reload(data)

demand_df = data.GetDataForRange((2017, 1, 1), (2017, 2, 1), GetDemand)
demand_df.head()

               NI Load (MW)  SI Load (MW)
tpid
2017_01_01_01      1785.563      1451.458
2017_01_01_02      1681.077      1429.073
2017_01_01_03      1584.498      1404.121
2017_01_01_04      1518.693      1371.177
2017_01_01_05      1476.998      1350.335

In [5]:
demand_df.tail()

               NI Load (MW)  SI Load (MW)
tpid
2017_02_01_44      2638.731      1749.256
2017_02_01_45      2531.563      1715.873
2017_02_01_46      2376.252      1662.269
2017_02_01_47      2246.570      1660.014
2017_02_01_48      2155.581      1631.350

In [ ]:
from DANZEM import offers

In [2]:
from DANZEM import generation

def GetGeneration(day):
    df = data.GetGenerationFile(day)
    return generation.ProcessGenerationFile(df)

gen_df = data.GetDataForRange((2017, 1), (2017, 3), GetGeneration)
gen_df.head()

,Site_Code,PointOfConnection,Trader,Gen_Code,Fuel_Code,Tech_Code,Generation (MW),tpid
0,ARA,ARA2201,MRPL,aratiatia,Hydro,Hydro,23.02,2017_01_01_01
1,ARA,ARA2201,MRPL,aratiatia,Hydro,Hydro,23.14,2017_01_02_01
2,ARA,ARA2201,MRPL,aratiatia,Hydro,Hydro,22.18,2017_01_03_01
3,ARA,ARA2201,MRPL,aratiatia,Hydro,Hydro,27.94,2017_01_04_01
4,ARA,ARA2201,MRPL,aratiatia,Hydro,Hydro,39.36,2017_01_05_01

In [3]:
gen_df.tail()

,Site_Code,PointOfConnection,Trader,Gen_Code,Fuel_Code,Tech_Code,Generation (MW),tpid
94075,WWD,WWD1103,MERI,west_wind,Wind,Wind,0.0,2017_02_24_48
94076,WWD,WWD1103,MERI,west_wind,Wind,Wind,0.0,2017_02_25_48
94077,WWD,WWD1103,MERI,west_wind,Wind,Wind,0.0,2017_02_26_48
94078,WWD,WWD1103,MERI,west_wind,Wind,Wind,0.0,2017_02_27_48
94079,WWD,WWD1103,MERI,west_wind,Wind,Wind,0.0,2017_02_28_48

In [5]:
importlib.reload(data)

data.AddIslandSeries(gen_df, 'PointOfConnection')
gen_df.head()

KeyError: 'WPG'

In [7]:
gen_df[gen_df['PointOfConnection'].apply(lambda x: x.startswith('WPG'))]

,Site_Code,PointOfConnection,Trader,Gen_Code,Fuel_Code,Tech_Code,Generation (MW),tpid
1922,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,30.817628,2017_01_01_01
1923,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,29.174270,2017_01_02_01
1924,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,14.768012,2017_01_03_01
1925,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,33.416558,2017_01_04_01
1926,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,42.041652,2017_01_05_01
1927,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,7.796053,2017_01_06_01
1928,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,40.865315,2017_01_07_01
1929,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,14.789623,2017_01_08_01
1930,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,34.378320,2017_01_09_01
1931,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,12.644446,2017_01_10_01
1932,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,6.923752,2017_01_11_01
1933,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,27.474544,2017_01_12_01
1934,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,30.696126,2017_01_13_01
1935,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,15.073857,2017_01_14_01
1936,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,11.510938,2017_01_15_01
1937,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,11.691756,2017_01_16_01
1938,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,25.170925,2017_01_17_01
1939,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,0.179034,2017_01_18_01
1940,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,29.206940,2017_01_19_01
1941,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,36.687252,2017_01_20_01
1942,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,5.449652,2017_01_21_01
1943,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,11.009435,2017_01_22_01
1944,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,33.668406,2017_01_23_01
1945,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,24.119472,2017_01_24_01
1946,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,37.993201,2017_01_25_01
1947,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,39.705543,2017_01_26_01
1948,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,39.642435,2017_01_27_01
1949,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,7.123265,2017_01_28_01
1950,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,7.336566,2017_01_29_01
1951,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,7.949219,2017_01_30_01
...,...,...,...,...,...,...,...,...
91922,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,2.823020,2017_02_27_47
91923,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,22.145200,2017_02_28_47
93856,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,2.081980,2017_02_01_48
93857,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,39.585000,2017_02_02_48
93858,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,13.172320,2017_02_03_48
93859,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,31.861600,2017_02_04_48
93860,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,14.984320,2017_02_05_48
93861,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,35.194800,2017_02_06_48
93862,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,46.973800,2017_02_07_48
93863,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,12.538440,2017_02_08_48
93864,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,21.532400,2017_02_09_48
93865,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,18.518520,2017_02_10_48
93866,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,9.121160,2017_02_11_48
93867,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,18.161840,2017_02_12_48
93868,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,1.162132,2017_02_13_48
93869,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,19.881120,2017_02_14_48
93870,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,0.062236,2017_02_15_48
93871,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,19.701140,2017_02_16_48
93872,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,16.627040,2017_02_17_48
93873,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,11.787240,2017_02_18_48
93874,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,13.982180,2017_02_19_48
93875,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,34.389600,2017_02_20_48
93876,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,32.879200,2017_02_21_48
93877,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,27.769000,2017_02_22_48
93878,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,25.788400,2017_02_23_48
93879,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,8.305400,2017_02_24_48
93880,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,1.227822,2017_02_25_48
93881,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,0.778820,2017_02_26_48
93882,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,3.470940,2017_02_27_48
93883,WPI,WPG0331,TRPG,waipori,Hydro,Hydro,22.202400,2017_02_28_48

In [9]:
offers_df = data.GetOfferFile((2017, 1, 1))
offers_df.head()

,PointOfConnection,Unit,OtherGridEntity,Trader,ProductType,ProductClass,ProductSubClass,ProductCategory,UTCSubmissionDate,UTCSubmissionTime,...,IsLatest,TradingDate,TradingPeriod,Band,MaximumRampUpMegawattPerHour,MaximumRampDownMegawattPerHour,PartiallyLoadedSpinningReservePercent,MaximumOutputMegawatt,Megawatt,DollarsPerMegawattHour
0,GLN0332,GLN0,NaN,ALNT,Energy,Injection,NaN,NaN,2016-12-29,08:20:31.0000000,...,N,2017-01-01,1,1,999.0,999.0,NaN,62.0,62.0,0.0
1,GLN0332,GLN0,NaN,ALNT,Energy,Injection,NaN,NaN,2016-12-29,08:20:31.0000000,...,N,2017-01-01,1,2,999.0,999.0,NaN,62.0,0.0,0.0
2,GLN0332,GLN0,NaN,ALNT,Energy,Injection,NaN,NaN,2016-12-29,08:20:31.0000000,...,N,2017-01-01,1,3,999.0,999.0,NaN,62.0,0.0,0.0
3,GLN0332,GLN0,NaN,ALNT,Energy,Injection,NaN,NaN,2016-12-29,08:20:31.0000000,...,N,2017-01-01,1,4,999.0,999.0,NaN,62.0,0.0,0.0
4,GLN0332,GLN0,NaN,ALNT,Energy,Injection,NaN,NaN,2016-12-29,08:20:31.0000000,...,N,2017-01-01,1,5,999.0,999.0,NaN,62.0,0.0,0.0

In [10]:
offers_df[offers_df['PointOfConnection'].apply(lambda x: x.startswith('WPG'))]

Empty DataFrame
Columns: [PointOfConnection, Unit, OtherGridEntity, Trader, ProductType, ProductClass, ProductSubClass, ProductCategory, UTCSubmissionDate, UTCSubmissionTime, SubmissionOrder, IsLatest, TradingDate, TradingPeriod, Band, MaximumRampUpMegawattPerHour, MaximumRampDownMegawattPerHour, PartiallyLoadedSpinningReservePercent, MaximumOutputMegawatt, Megawatt, DollarsPerMegawattHour]
Index: []

[0 rows x 21 columns]

In [12]:
offers_df['Trader'].unique()

array(['ALNT', 'CNTP', 'CTCT', 'ERGY', 'GENE', 'KING', 'MERI', 'MRPL',
       'NAPJ', 'NTHP', 'NZWF', 'POCO', 'PPAC', 'PUNZ', 'SKOG', 'TODD',
       'TRUS', 'TUAR', 'VCTR', 'VWEN', 'WNET'], dtype=object)

In [13]:
offers_df[offers_df['Trader'] == 'TRUS'].groupby('PointOfConnection').first()

,Unit,OtherGridEntity,Trader,ProductType,ProductClass,ProductSubClass,ProductCategory,UTCSubmissionDate,UTCSubmissionTime,SubmissionOrder,IsLatest,TradingDate,TradingPeriod,Band,MaximumRampUpMegawattPerHour,MaximumRampDownMegawattPerHour,PartiallyLoadedSpinningReservePercent,MaximumOutputMegawatt,Megawatt,DollarsPerMegawattHour
PointOfConnection,,,,,,,,,,,,,,,,,,,,
ARG1101,BRR0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-29,06:06:58.0000000,1,Y,2017-01-01,1,1,300.0,300.0,NaN,12.0,0.000,0.01
ASB0661,HBK0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-10-06,22:28:04.0000000,1,Y,2017-01-01,1,1,999.0,999.0,NaN,0.0,0.000,0.00
BPE0331,TWF0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-28,14:15:40.0000000,1,N,2017-01-01,1,1,9999.0,9999.0,NaN,35.0,15.652,0.01
BWK1101,WPI0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-29,06:26:59.0000000,1,Y,2017-01-01,1,1,999.0,999.0,NaN,55.0,0.000,0.01
COL0661,COL0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-29,06:09:49.0000000,1,Y,2017-01-01,1,1,180.0,60.0,NaN,39.0,10.000,5.00
HWA1101,PTA1,NaN,TRUS,Energy,Injection,FIR,PLS,2016-12-29,06:25:07.0000000,1,Y,2017-01-01,1,1,300.0,300.0,250.0,11.0,3.000,0.00
HWB0331,MAH0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-28,14:15:40.0000000,1,N,2017-01-01,1,1,9999.0,9999.0,NaN,36.0,16.908,0.01
KIN0112,KIN0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-28,08:58:56.0000000,1,Y,2017-01-01,1,1,60.0,60.0,NaN,40.0,34.000,0.00
KUM0661,KUM0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-28,06:16:12.0000000,1,Y,2017-01-01,1,1,12.0,20.0,NaN,7.0,0.000,0.00
LTN0331,TWF0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-28,14:15:40.0000000,1,N,2017-01-01,1,1,9999.0,9999.0,NaN,34.0,15.351,0.01
MAT1101,MAT0,NaN,TRUS,Energy,Injection,FIR,PLS,2016-12-28,07:57:01.0000000,1,Y,2017-01-01,1,1,999.0,8.0,42.0,80.0,19.000,0.00
NSY0331,PAE0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-29,08:04:53.0000000,1,N,2017-01-01,1,1,999.0,999.0,NaN,12.0,4.500,0.00
ROT1101,WHE0,NaN,TRUS,Energy,Injection,FIR,PLS,2016-12-27,06:35:43.0000000,1,N,2017-01-01,1,1,999.0,999.0,0.0,26.0,12.000,0.00
STK0661,COB0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-28,06:10:34.0000000,1,Y,2017-01-01,1,1,90.0,90.0,NaN,32.0,10.000,18.53
TGA0331,KMI0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-29,10:01:41.0000000,1,Y,2017-01-01,1,1,999.0,999.0,NaN,42.0,0.000,0.00
TWC2201,TWF0,NaN,TRUS,Energy,Injection,NaN,NaN,2016-12-28,14:15:40.0000000,1,N,2017-01-01,1,1,9999.0,9999.0,NaN,93.0,32.178,0.01

In [33]:
co_df = data.GetClearedOffersFile((2017, 1, 1))
co_df = co_df[co_df['ClearedEnergy (MW)'] != 0.0]
co_df.head()

,Date,TradingPeriod,Island,PointOfConnection,Trader,Type,ClearedEnergy (MW),ClearedFIR (MW),ClearedSIR (MW)
0,2017-01-01,1,NI,GLN0332 GLN0,ALNT,ENOF,46.0,0.0,0.0
2,2017-01-01,1,SI,CYD2201 CYD0,CTCT,ENOF,300.0,0.0,0.0
3,2017-01-01,1,NI,OKI2201 OKI0,CTCT,ENOF,41.0,0.0,0.0
4,2017-01-01,1,NI,PPI2201 PPI0,CTCT,ENOF,48.0,0.0,0.0
5,2017-01-01,1,SI,ROX1101 ROX0,CTCT,ENOF,40.0,0.0,0.0

In [34]:
tp1 = co_df[co_df['TradingPeriod'] == 1]
tp1['PointOfConnection'].unique()

array(['GLN0332 GLN0', 'CYD2201 CYD0', 'OKI2201 OKI0', 'PPI2201 PPI0',
       'ROX1101 ROX0', 'ROX2201 ROX0', 'THI2201 THI1', 'THI2201 THI2',
       'TWH0331 TRC1', 'WRK0331 TAA0', 'WRK2201 WRK0', 'HLY2201 HLY5',
       'RPO2201 RPO0', 'TKA0111 TKA1', 'TKB2201 TKB1', 'TUI1101 PRI0',
       'TUI1101 TUI0', 'MHO0331 MHO0', 'AVI2201 AVI0', 'BEN2202 BEN0',
       'HWA1102 WAA1', 'MAN2201 MAN0', 'OHA2201 OHA0', 'OHB2201 OHB0',
       'OHC2201 OHC0', 'WTK0111 WTK0', 'ARA2201 ARA0', 'ARI1101 ARI0',
       'ARI1102 ARI0', 'ATI2201 ATI0', 'KAW1101 KAG0', 'KPO1101 KPO0',
       'MTI2201 MTI0', 'NAP2202 NTM0', 'OHK2201 OHK0', 'WKM2201 WKM0',
       'WPA2201 WPA0', 'WRK0331 RKA0', 'MAT1101 ANI0', 'KAW0112 DLS0',
       'KAW0113 DLS1', 'KAW0112 ONU0', 'HWA1102 WAA0', 'KPA1101 KPI1',
       'COL0661 COL0', 'HWA1101 PTA1', 'KUM0661 KUM0', 'MAT1101 MAT0',
       'NSY0331 PAE0', 'ROT1101 WHE0', 'STK0661 COB0', 'WKM2201 MOK0',
       'NAP2201 NAP0'], dtype=object)

In [35]:
tp1.groupby('PointOfConnection').first()

,Date,TradingPeriod,Island,Trader,Type,ClearedEnergy (MW),ClearedFIR (MW),ClearedSIR (MW)
PointOfConnection,,,,,,,,
ARA2201 ARA0,2017-01-01,1,NI,MRPL,ENOF,26.000,0.0,0.0
ARI1101 ARI0,2017-01-01,1,NI,MRPL,ENOF,46.000,0.0,0.0
ARI1102 ARI0,2017-01-01,1,NI,MRPL,ENOF,21.000,0.0,0.0
ATI2201 ATI0,2017-01-01,1,NI,MRPL,ENOF,20.000,0.0,0.0
AVI2201 AVI0,2017-01-01,1,SI,MERI,ENOF,32.829,0.0,0.0
BEN2202 BEN0,2017-01-01,1,SI,MERI,ENOF,143.000,0.0,0.0
COL0661 COL0,2017-01-01,1,SI,TRUS,ENOF,39.000,0.0,0.0
CYD2201 CYD0,2017-01-01,1,SI,CTCT,ENOF,300.000,0.0,0.0
GLN0332 GLN0,2017-01-01,1,NI,ALNT,ENOF,46.000,0.0,0.0
HLY2201 HLY5,2017-01-01,1,NI,GENE,ENOF,260.000,0.0,0.0
HWA1101 PTA1,2017-01-01,1,NI,TRUS,ENOF,3.000,0.0,0.0
HWA1102 WAA0,2017-01-01,1,NI,TODD,ENOF,4.000,0.0,0.0
HWA1102 WAA1,2017-01-01,1,NI,MERI,ENOF,4.000,0.0,0.0
KAW0112 DLS0,2017-01-01,1,NI,SKOG,ENDL,-38.000,0.0,0.0
KAW0112 ONU0,2017-01-01,1,NI,SKOG,ENOF,51.000,0.0,0.0
KAW0113 DLS1,2017-01-01,1,NI,SKOG,ENDL,-36.000,0.0,0.0
KAW1101 KAG0,2017-01-01,1,NI,MRPL,ENOF,105.000,0.0,0.0
KPA1101 KPI1,2017-01-01,1,NI,TODD,ENOF,6.300,0.0,0.0
KPO1101 KPO0,2017-01-01,1,NI,MRPL,ENOF,46.000,0.0,0.0
KUM0661 KUM0,2017-01-01,1,SI,TRUS,ENOF,6.000,0.0,0.0
MAN2201 MAN0,2017-01-01,1,SI,MERI,ENOF,555.000,0.0,0.0
MAT1101 ANI0,2017-01-01,1,NI,PUNZ,ENOF,11.500,0.0,0.0
MAT1101 MAT0,2017-01-01,1,NI,TRUS,ENOF,19.000,0.0,0.0
MHO0331 MHO0,2017-01-01,1,NI,KING,ENOF,27.000,0.0,0.0
MTI2201 MTI0,2017-01-01,1,NI,MRPL,ENOF,49.000,0.0,0.0
NAP2201 NAP0,2017-01-01,1,NI,NAPJ,ENOF,140.000,0.0,0.0
NAP2202 NTM0,2017-01-01,1,NI,MRPL,ENOF,85.000,0.0,0.0
NSY0331 PAE0,2017-01-01,1,SI,TRUS,ENOF,4.000,0.0,0.0
OHA2201 OHA0,2017-01-01,1,SI,MERI,ENOF,38.965,0.0,0.0
OHB2201 OHB0,2017-01-01,1,SI,MERI,ENOF,31.603,0.0,0.0
OHC2201 OHC0,2017-01-01,1,SI,MERI,ENOF,31.603,0.0,0.0
OHK2201 OHK0,2017-01-01,1,NI,MRPL,ENOF,18.771,0.0,0.0
OKI2201 OKI0,2017-01-01,1,NI,CTCT,ENOF,41.000,0.0,0.0
PPI2201 PPI0,2017-01-01,1,NI,CTCT,ENOF,48.000,0.0,0.0
ROT1101 WHE0,2017-01-01,1,NI,TRUS,ENOF,6.000,0.0,0.0
ROX1101 ROX0,2017-01-01,1,SI,CTCT,ENOF,40.000,0.0,0.0
ROX2201 ROX0,2017-01-01,1,SI,CTCT,ENOF,196.000,0.0,0.0
RPO2201 RPO0,2017-01-01,1,NI,GENE,ENOF,65.000,0.0,0.0
STK0661 COB0,2017-01-01,1,SI,TRUS,ENOF,32.000,0.0,0.0
THI2201 THI1,2017-01-01,1,NI,CTCT,ENOF,84.000,0.0,0.0
THI2201 THI2,2017-01-01,1,NI,CTCT,ENOF,84.000,0.0,0.0
TKA0111 TKA1,2017-01-01,1,SI,GENE,ENOF,23.000,0.0,0.0
TKB2201 TKB1,2017-01-01,1,SI,GENE,ENOF,128.000,0.0,0.0
TUI1101 PRI0,2017-01-01,1,NI,GENE,ENOF,6.000,0.0,0.0
TUI1101 TUI0,2017-01-01,1,NI,GENE,ENOF,8.000,0.0,0.0
TWH0331 TRC1,2017-01-01,1,NI,CTCT,ENOF,43.000,0.0,0.0
WKM2201 MOK0,2017-01-01,1,NI,TUAR,ENOF,103.000,0.0,0.0
WKM2201 WKM0,2017-01-01,1,NI,MRPL,ENOF,46.000,0.0,0.0
WPA2201 WPA0,2017-01-01,1,NI,MRPL,ENOF,22.000,0.0,0.0
WRK0331 RKA0,2017-01-01,1,NI,MRPL,ENOF,26.000,0.0,0.0
WRK0331 TAA0,2017-01-01,1,NI,CTCT,ENOF,22.000,0.0,0.0
WRK2201 WRK0,2017-01-01,1,NI,CTCT,ENOF,106.000,0.0,0.0
WTK0111 WTK0,2017-01-01,1,SI,MERI,ENOF,35.000,0.0,0.0

In [36]:
tp1[tp1['PointOfConnection'].apply(lambda x: x.startswith('WP'))]

,Date,TradingPeriod,Island,PointOfConnection,Trader,Type,ClearedEnergy (MW),ClearedFIR (MW),ClearedSIR (MW)
52,2017-01-01,1,NI,WPA2201 WPA0,MRPL,ENOF,22.0,0.0,0.0

In [37]:
lgp_df = data.GetLGPFile((2017, 1, 1))
lgp_df.head()

,Date,TradingPeriod,Island,PointOfConnection,Load (MW),Generation (MW),Price ($/MWh)
0,2017-01-01,1,SI,ABY0111,3.239,0.0,35.95
1,2017-01-01,2,SI,ABY0111,3.143,0.0,41.65
2,2017-01-01,3,SI,ABY0111,3.045,0.0,26.58
3,2017-01-01,46,SI,ABY0111,3.362,0.0,35.01
4,2017-01-01,47,SI,ABY0111,3.451,0.0,35.53

In [43]:
cleared_set = set(co_df['PointOfConnection'].apply(lambda x: x.split()[0]))
gen_set = set(gen_df['PointOfConnection'][gen_df['tpid'].apply(lambda x: x.endswith('01'))])
lgp_set = set(lgp_df['PointOfConnection'][lgp_df['TradingPeriod'] == 1].apply(lambda x: x.split()[0]))
cleared_set - gen_set

{'KAW0112', 'KAW0113', 'KUM0661', 'STK0661'}

In [39]:
gen_set - cleared_set

{'ARG1101',
 'ASB0661',
 'BPE0331',
 'BWK1101',
 'KIN0112',
 'KOE1101',
 'LTN0331',
 'MKE1101',
 'NMA0331',
 'SFD2201',
 'TGA0331',
 'TKU2201',
 'TWC2201',
 'WDV1101',
 'WHI2201',
 'WPG0331',
 'WWD1102',
 'WWD1103'}

In [40]:
gen_set - lgp_set

{'BWK1101', 'TKU2201', 'WPG0331'}

In [41]:
cleared_set - lgp_set

set()

In [45]:
cleared_but_no_gen = cleared_set - gen_set
co_df[co_df['PointOfConnection'].apply(lambda x: x.split()[0] in cleared_but_no_gen)]

,Date,TradingPeriod,Island,PointOfConnection,Trader,Type,ClearedEnergy (MW),ClearedFIR (MW),ClearedSIR (MW)
64,2017-01-01,1,NI,KAW0112 DLS0,SKOG,ENDL,-38.00,0.0,0.0
65,2017-01-01,1,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
66,2017-01-01,1,NI,KAW0112 ONU0,SKOG,ENOF,51.00,0.0,0.0
72,2017-01-01,1,SI,KUM0661 KUM0,TRUS,ENOF,6.00,0.0,0.0
76,2017-01-01,1,SI,STK0661 COB0,TRUS,ENOF,32.00,0.0,0.0
151,2017-01-01,2,NI,KAW0112 DLS0,SKOG,ENDL,-38.00,0.0,0.0
152,2017-01-01,2,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
153,2017-01-01,2,NI,KAW0112 ONU0,SKOG,ENOF,51.00,0.0,0.0
159,2017-01-01,2,SI,KUM0661 KUM0,TRUS,ENOF,6.00,0.0,0.0
163,2017-01-01,2,SI,STK0661 COB0,TRUS,ENOF,32.00,0.0,0.0
228,2017-01-01,3,NI,KAW0112 DLS0,SKOG,ENDL,-38.00,0.0,0.0
229,2017-01-01,3,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
230,2017-01-01,3,NI,KAW0112 ONU0,SKOG,ENOF,51.00,0.0,0.0
236,2017-01-01,3,SI,KUM0661 KUM0,TRUS,ENOF,6.00,0.0,0.0
240,2017-01-01,3,SI,STK0661 COB0,TRUS,ENOF,32.00,0.0,0.0
310,2017-01-01,4,NI,KAW0112 DLS0,SKOG,ENDL,-38.00,0.0,0.0
311,2017-01-01,4,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
312,2017-01-01,4,NI,KAW0112 ONU0,SKOG,ENOF,51.00,0.0,0.0
318,2017-01-01,4,SI,KUM0661 KUM0,TRUS,ENOF,6.00,0.0,0.0
322,2017-01-01,4,SI,STK0661 COB0,TRUS,ENOF,32.00,0.0,0.0
390,2017-01-01,5,NI,KAW0112 DLS0,SKOG,ENDL,-38.00,0.0,0.0
391,2017-01-01,5,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
392,2017-01-01,5,NI,KAW0112 ONU0,SKOG,ENOF,51.00,0.0,0.0
398,2017-01-01,5,SI,KUM0661 KUM0,TRUS,ENOF,6.00,0.0,0.0
402,2017-01-01,5,SI,STK0661 COB0,TRUS,ENOF,32.00,0.0,0.0
470,2017-01-01,6,NI,KAW0112 DLS0,SKOG,ENDL,-38.00,0.0,0.0
471,2017-01-01,6,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
472,2017-01-01,6,NI,KAW0112 ONU0,SKOG,ENOF,51.00,0.0,0.0
478,2017-01-01,6,SI,KUM0661 KUM0,TRUS,ENOF,3.00,0.0,0.0
482,2017-01-01,6,SI,STK0661 COB0,TRUS,ENOF,23.57,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3647,2017-01-01,43,NI,KAW0112 DLS0,SKOG,ENDL,-30.00,0.0,0.0
3648,2017-01-01,43,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
3649,2017-01-01,43,NI,KAW0112 ONU0,SKOG,ENOF,47.00,0.0,0.0
3655,2017-01-01,43,SI,KUM0661 KUM0,TRUS,ENOF,6.00,0.0,0.0
3659,2017-01-01,43,SI,STK0661 COB0,TRUS,ENOF,32.00,0.0,0.0
3735,2017-01-01,44,NI,KAW0112 DLS0,SKOG,ENDL,-30.00,0.0,0.0
3736,2017-01-01,44,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
3737,2017-01-01,44,NI,KAW0112 ONU0,SKOG,ENOF,47.00,0.0,0.0
3742,2017-01-01,44,SI,KUM0661 KUM0,TRUS,ENOF,6.00,0.0,0.0
3746,2017-01-01,44,SI,STK0661 COB0,TRUS,ENOF,32.00,0.0,0.0
3817,2017-01-01,45,NI,KAW0112 DLS0,SKOG,ENDL,-30.00,0.0,0.0
3818,2017-01-01,45,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
3819,2017-01-01,45,NI,KAW0112 ONU0,SKOG,ENOF,47.00,0.0,0.0
3824,2017-01-01,45,SI,KUM0661 KUM0,TRUS,ENOF,6.00,0.0,0.0
3828,2017-01-01,45,SI,STK0661 COB0,TRUS,ENOF,32.00,0.0,0.0
3897,2017-01-01,46,NI,KAW0112 DLS0,SKOG,ENDL,-30.00,0.0,0.0
3898,2017-01-01,46,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
3899,2017-01-01,46,NI,KAW0112 ONU0,SKOG,ENOF,47.00,0.0,0.0
3904,2017-01-01,46,SI,KUM0661 KUM0,TRUS,ENOF,6.00,0.0,0.0
3908,2017-01-01,46,SI,STK0661 COB0,TRUS,ENOF,29.00,0.0,0.0
3975,2017-01-01,47,NI,KAW0112 DLS0,SKOG,ENDL,-30.00,0.0,0.0
3976,2017-01-01,47,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
3977,2017-01-01,47,NI,KAW0112 ONU0,SKOG,ENOF,47.00,0.0,0.0
3982,2017-01-01,47,SI,KUM0661 KUM0,TRUS,ENOF,6.00,0.0,0.0
3986,2017-01-01,47,SI,STK0661 COB0,TRUS,ENOF,29.00,0.0,0.0
4053,2017-01-01,48,NI,KAW0112 DLS0,SKOG,ENDL,-30.00,0.0,0.0
4054,2017-01-01,48,NI,KAW0113 DLS1,SKOG,ENDL,-36.00,0.0,0.0
4055,2017-01-01,48,NI,KAW0112 ONU0,SKOG,ENOF,47.00,0.0,0.0
4060,2017-01-01,48,SI,KUM0661 KUM0,TRUS,ENOF,6.00,0.0,0.0
4064,2017-01-01,48,SI,STK0661 COB0,TRUS,ENOF,20.00,0.0,0.0

In [50]:
co_df[(co_df['PointOfConnection'].apply(lambda x: x.startswith('KAW'))) & (co_df['TradingPeriod'] == 1)]

,Date,TradingPeriod,Island,PointOfConnection,Trader,Type,ClearedEnergy (MW),ClearedFIR (MW),ClearedSIR (MW)
46,2017-01-01,1,NI,KAW1101 KAG0,MRPL,ENOF,105.0,0.0,0.0
64,2017-01-01,1,NI,KAW0112 DLS0,SKOG,ENDL,-38.0,0.0,0.0
65,2017-01-01,1,NI,KAW0113 DLS1,SKOG,ENDL,-36.0,0.0,0.0
66,2017-01-01,1,NI,KAW0112 ONU0,SKOG,ENOF,51.0,0.0,0.0

In [49]:
lgp_df[(lgp_df['PointOfConnection'].apply(lambda x: x.startswith('KAW'))) & (lgp_df['TradingPeriod'] == 1)]

,Date,TradingPeriod,Island,PointOfConnection,Load (MW),Generation (MW),Price ($/MWh)
1886,2017-01-01,1,NI,KAW0111,7.577,0.0,34.64
8329,2017-01-01,1,NI,KAW0112 DLS0,38.000,0.0,34.59
8330,2017-01-01,1,NI,KAW0112 ONU0,0.000,51.0,34.59
9766,2017-01-01,1,NI,KAW0113 DLS1,36.000,0.0,34.84
9767,2017-01-01,1,NI,KAW1101 KAG0,0.000,105.0,34.61

In [52]:
gen_df[(gen_df['PointOfConnection'].apply(lambda x: x.startswith('KAW'))) & (gen_df['tpid'] == '2017_01_01_01')]

,Site_Code,PointOfConnection,Trader,Gen_Code,Fuel_Code,Tech_Code,Generation (MW),tpid
589,KAG,KAW1101,KRGL,kawerau_new,Geo,Geo,104.284,2017_01_01_01

In [25]:
from DANZEM import nodes

nodes.GetWindNodes()

{'BPE0331',
 'BPE0331 TWF0',
 'HWB0331',
 'HWB0331 MAH0',
 'LTN0331',
 'LTN0331 TWF0',
 'NMA0331',
 'NMA0331 WHL0',
 'TWC2201',
 'TWC2201 NZW0',
 'TWC2201 TWF0',
 'TWH0331',
 'TWH0331 TUK0',
 'WDV1101',
 'WDV1101 TAP0',
 'WIL0331',
 'WIL0331 MCK0',
 'WWD1102',
 'WWD1102 WWD0',
 'WWD1103',
 'WWD1103 WWD0'}

In [2]:
from DANZEM import offers
from DANZEM import utils
from DANZEM import data

import importlib
#importlib.reload(offers)

utils.SetDir('C:\\Users\\tahjaa\\Documents\\Research\\DANZEM\\DANZEM\\data')

def DispatchByIsland(ymd):
    lgp_df = data.GetLGPFile(ymd)
    return offers.GetDispatchByIsland(lgp_df)

stacks = DispatchByIsland((2017, 1, 1))
stacks.head()

               NI Dispatch (MW)  SI Dispatch (MW)
tpid
2017_01_01_01          1698.571          1636.000
2017_01_01_02          1641.093          1559.127
2017_01_01_03          1596.127          1478.000
2017_01_01_04          1553.251          1419.000
2017_01_01_05          1510.442          1397.000